opt_in_rules:
  - empty_count
  - sorted_imports

disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name
  - type_name
  - orphaned_doc_comment

included:
  - AURORA

function_body_length: 60
