default_platform(:ios)

APP_IDENTIFIER = "eu.inscico.aurora-app"
TEAM_ID = "UNLWT228LJ"

platform :ios do

  desc "Build App"
  lane :build_app_lane do
    # Initialize fastlane keychain name/password
    FASTLANE_KEYCHAIN = "fastlane"
    # Create Keychain
    create_keychain(
      name: FASTLANE_KEYCHAIN,
      password: FASTLANE_KEYCHAIN,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    # Authenticate with App Store Connect
    authenticate_with_app_store_connect
    # Increment build number using lastest TestFlight build number
    increment_build_number(
      build_number: latest_testflight_build_number(
        app_identifier: APP_IDENTIFIER,
        initial_build_number: 0,
        team_id: TEAM_ID
      ) + 1,
      skip_info_plist: true
    )
    # Sync Code Signing / Match
    sync_code_signing(
      type: "appstore",
      team_id: TEAM_ID,
      app_identifier: APP_IDENTIFIER,
      readonly: true,
      keychain_name: FASTLANE_KEYCHAIN,
      keychain_password: FASTLANE_KEYCHAIN,
      git_url: "https://github.com/AURORA-H2020/AURORA-iOS-Certificates.git",
      git_branch: "main"
    )
    # Update Code Signing settings
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: TEAM_ID,
      code_sign_identity: "iPhone Distribution",
      profile_name: ENV["sigh_#{APP_IDENTIFIER}_appstore_profile-name"]
    )
    # Build App
    build_ios_app(
      scheme: "AURORA",
      output_name: "app",
      export_method: "app-store",
      derived_data_path: "build"
    )
  end

  desc "Upload to TestFlight"
  lane :upload_to_test_flight_lane do
    # Authenticate with App Store Connect
    authenticate_with_app_store_connect
    # Upload to TestFlight
    upload_to_testflight(
      app_identifier: APP_IDENTIFIER,
      ipa: "app.ipa",
      team_id: TEAM_ID,
      groups: ["External-Tester"],
      reject_build_waiting_for_review: true,
    )
  end

  desc "Upload Debug Symbols to Firebase Crashlytics"
  lane :upload_debug_symbols_to_crashlytics_lane do
    # Upload debug symbols to Firebase Crashlytics
    upload_symbols_to_crashlytics(
      dsym_path: "app.app.dSYM.zip",
      gsp_path: "AURORA/Resources/GoogleService-Info.plist",
      binary_path: "upload-symbols"
    )
  end

  desc "Authenticate with App Store Connect using API Key"
  private_lane :authenticate_with_app_store_connect do
    # Authenticate using App Store Connect API Key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_PRIVATE_KEY"]
    )
  end

  desc "Generate app screenshots and apply frames"
  lane :screenshots do
    # The devices to capture screenshots for
    devices = [
      "iPhone 14 Pro Max",
      "iPhone 8 Plus",
      "iPad Pro (12.9-inch) (6th generation)",
      "iPad Pro (11-inch) (4th generation)"
    ]
    # The languages
    languages = [
      "en-US",
      "de-DE",
      "da-DK",
      "es-ES",
      "sl-SL",
      "pt-PT"
    ]
    # The scheme
    scheme = "AURORA"
    # The derived data path
    derivedDataPath = "./build"
    # Build tests
    run_tests(
      scheme: scheme,
      devices: devices,
      derived_data_path: derivedDataPath,
      build_for_testing: true
    )
    # Run tests and capture screenshots
    capture_screenshots(
      devices: devices,
      languages: languages,
      launch_arguments: [
        "-ui_test_login_email #{ENV['FASTLANE_SNAPSHOT_UI_TEST_EMAIL']} -ui_test_login_password #{ENV['FASTLANE_SNAPSHOT_UI_TEST_PASSWORD']}"
      ],
      output_directory: "./fastlane/screenshots",
      skip_open_summary: true,
      clear_previous_screenshots: true,
      override_status_bar: true,
      test_without_building: true,
      scheme: scheme,
      stop_after_first_error: true,
      derived_data_path: derivedDataPath
    )
    # Frame screenshots
    frame_screenshots
  end

end
