# A list of devices you want to take the screenshots from
devices([
   "iPhone 14 Plus",
   "iPhone 8 Plus",
   "iPad Pro (12.9-inch) (6th generation)",
   "iPad Pro (12.9-inch) (2nd generation)"
])

languages([
   "en-UK",
   "de-DE",
   "da-DK",
   "es-ES",
   "sl-SL",
   "pt-PT"
])

# The name of the scheme which contains the UI Tests
scheme("AURORA")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch.
launch_arguments([
   "-email #{ENV['FASTLANE_SNAPSHOT_UI_TEST_EMAIL']}", 
   "-password #{ENV['FASTLANE_SNAPSHOT_UI_TEST_PASSWORD']}"
])

# Clean build
clean(true)

# Erase simulator
erase_simulator(true)
