import SwiftUI

// MARK: - ConsumptionView

/// The ConsumptionView
struct ConsumptionView {
    
    /// The Consumption
    let consumption: Consumption
    
    /// The consumption form sheet mode
    @State
    private var consumptionFormSheetMode: ConsumptionFormSheetMode?
    
    /// Bool value if delete confirmation dialog is presented
    @State
    private var isDeleteConfirmationDialogPresented = false
    
    /// The photovoltaic plant investment if the consumption is generated by one.
    @State
    private var photovoltaicPlantInvestment: Result<PhotovoltaicPlantInvestment, Error>?
    
    /// The photovoltaic plant if the consumption is generated by one.
    @State
    private var photovoltaicPlant: Result<PhotovoltaicPlant, Error>?
    
    /// The dismiss action
    @Environment(\.dismiss)
    private var dismiss
    
    /// The locale.
    @Environment(\.locale)
    private var locale
    
    /// The Firebase instance.
    @EnvironmentObject
    private var firebase: Firebase
    
}

// MARK: - ConsumptionFormSheetMode

private extension ConsumptionView {
    
    /// A consumption form sheet mode
    enum ConsumptionFormSheetMode: String, Hashable, Identifiable {
        /// Edit
        case edit
        /// Duplicate
        case duplicate
        
        /// The stable identity of the entity associated with this instance.
        var id: RawValue {
            self.rawValue
        }
    }
    
}

// MARK: - Load Photovoltaic Data

private extension ConsumptionView {
    
    /// Loads the photovoltaic plant and investment, if the consumption was generated by a photovoltaic plant.
    func loadPhotovoltaicData() async {
        // Verify a photovoltaic plant investment entity reference is available
        guard let photovoltaicPlantInvestmentEntityReference = self.consumption.generatedByPvInvestmentId else {
            // Otherwise clear state and return out of function
            self.photovoltaicPlantInvestment = nil
            self.photovoltaicPlant = nil
            return
        }
        // Declare photovoltaic plant investment
        let photovoltaicPlantInvestment: PhotovoltaicPlantInvestment
        do {
            // Try to load investement
            photovoltaicPlantInvestment = try await self.firebase
                .firestore
                .get(
                    PhotovoltaicPlantInvestment.self,
                    context: .current(),
                    id: photovoltaicPlantInvestmentEntityReference.id
                )
        } catch {
            // Set error
            self.photovoltaicPlantInvestment = .failure(error)
            self.photovoltaicPlant = .failure(error)
            // Return out of function
            return
        }
        // Set investment
        self.photovoltaicPlantInvestment = .success(photovoltaicPlantInvestment)
        do {
            // Try to load plant
            self.photovoltaicPlant = .success(
                try await self.firebase
                    .firestore
                    .get(
                        PhotovoltaicPlant.self,
                        id: photovoltaicPlantInvestment.pvPlant.id
                    )
            )
        } catch {
            // Set error
            self.photovoltaicPlant = .failure(error)
        }
    }
    
}

// MARK: - View

extension ConsumptionView: View {
    
    /// The content and behavior of the view.
    var body: some View {
        List {
            if self.consumption.generatedByPvInvestmentId != nil {
                Section {
                } footer: {
                    VStack(spacing: 14) {
                        HStack {
                            Image(
                                systemName: "sunrise"
                            )
                            .font(.title)
                            .foregroundStyle(.yellow)
                            Text("""
                            This entry was created by your PV investment. It will update automatically with the latest data.
                            """)
                            .multilineTextAlignment(.leading)
                        }
                        Button {
                            #warning("Present edit pv investment form")
                        } label: {
                            Text("Manage Investment")
                                .font(.subheadline)
                        }
                        .buttonStyle(.bordered)
                        .buttonBorderShape(.capsule)
                        .tint(.accentColor)
                    }
                    .padding(.bottom, 6)
                }
            }
            Section {
                Entry {
                    Text(self.consumption.formatted())
                } label: {
                    Text(self.consumption.localizedTitle)
                }
                if let carbonEmissions = self.consumption.carbonEmissions {
                    Entry {
                        Text(
                            ConsumptionMeasurement(
                                value: carbonEmissions,
                                unit: .kilograms
                            )
                            .converted(to: .init(locale: self.locale))
                            .formatted(isCarbonEmissions: true)
                        )
                    } label: {
                        Text("Carbon emissions")
                    }
                }
                if let photovoltaicPlant = try? self.photovoltaicPlant?.get() {
                    Entry {
                        Text(photovoltaicPlant.name)
                    } label: {
                        Text("Installation Site")
                    }
                }
                if self.consumption.generatedByPvInvestmentId == nil,
                   let energyExpended = self.consumption.energyExpended {
                    Entry {
                        Text(
                            ConsumptionMeasurement(
                                value: energyExpended,
                                unit: .kilowattHours
                            )
                            .converted(to: .init(locale: self.locale))
                            .formatted()
                        )
                    } label: {
                        Text("Energy usage")
                    }
                }
            }
            if let electricity = self.consumption.electricity {
                if self.consumption.generatedByPvInvestmentId == nil {
                    if let costs = electricity.costs {
                        Entry {
                            CurrencyText(costs)
                                .foregroundColor(.secondary)
                        } label: {
                            Text("Costs")
                        }
                    }
                    Entry {
                        Text(String(electricity.householdSize))
                            .foregroundColor(.secondary)
                    } label: {
                        Text("People in household")
                    }
                    if let electricitySource = electricity.electricitySource {
                        Entry {
                            Text(electricitySource.localizedString)
                                .foregroundColor(.secondary)
                        } label: {
                            Text("Electricity source")
                        }
                    }
                    if let energyExported = electricity.electricityExported {
                        Entry {
                            Text(
                                ConsumptionMeasurement(
                                    value: energyExported,
                                    unit: .kilowattHours
                                )
                                .converted(to: .init(locale: self.locale))
                                .formatted()
                            )
                            .foregroundColor(.secondary)
                        } label: {
                            Text("Energy exported")
                        }
                    }
                } else {
                    Entry {
                        Text("PV Investment")
                            .foregroundColor(.secondary)
                    } label: {
                        Text("Electricity source")
                    }
                }
                Entry {
                    Text(
                        electricity.startDate.dateValue(),
                        style: .date
                    )
                    .foregroundColor(.secondary)
                } label: {
                    Text("Beginning")
                }
                Entry {
                    Text(
                        electricity.endDate.dateValue(),
                        style: .date
                    )
                    .foregroundColor(.secondary)
                } label: {
                    Text("End")
                }
            } else if let heating = self.consumption.heating {
                if let costs = heating.costs {
                    Entry {
                        CurrencyText(costs)
                            .foregroundColor(.secondary)
                    } label: {
                        Text("Costs")
                    }
                }
                Entry {
                    Text(String(heating.householdSize))
                        .foregroundColor(.secondary)
                } label: {
                    Text("People in household")
                }
                Entry {
                    Text(
                        heating.startDate.dateValue(),
                        style: .date
                    )
                    .foregroundColor(.secondary)
                } label: {
                    Text("Beginning")
                }
                Entry {
                    Text(
                        heating.endDate.dateValue(),
                        style: .date
                    )
                    .foregroundColor(.secondary)
                } label: {
                    Text("End")
                }
                Entry {
                    Text(heating.heatingFuel.localizedString)
                        .foregroundColor(.secondary)
                } label: {
                    Text("Heating fuel")
                }
                if let districtHeatingSource = heating.districtHeatingSource {
                    Entry {
                        Text(districtHeatingSource.localizedString)
                            .foregroundColor(.secondary)
                    } label: {
                        Text("Heating source")
                    }
                }
            } else if let transportation = self.consumption.transportation {
                Entry {
                    Text(
                        transportation.dateOfTravel.dateValue(),
                        format: .dateTime
                    )
                    .foregroundColor(.secondary)
                } label: {
                    Text("Start of travel")
                }
                if let dateOfTravelEnd = transportation.dateOfTravelEnd {
                    Entry {
                        Text(
                            dateOfTravelEnd.dateValue(),
                            format: .dateTime
                        )
                        .foregroundColor(.secondary)
                    } label: {
                        Text("End of travel")
                    }
                }
                Entry {
                    Text(transportation.transportationType.localizedString)
                        .foregroundColor(.secondary)
                } label: {
                    Text("Transportation type")
                }
                if let privateVehicleOccupancy = transportation.privateVehicleOccupancy {
                    Entry {
                        Text(String(privateVehicleOccupancy))
                            .foregroundColor(.secondary)
                    } label: {
                        Text("Occupancy")
                    }
                } else if let publicVehicleOccupancy = transportation.publicVehicleOccupancy {
                    Entry {
                        Text(publicVehicleOccupancy.localizedString)
                            .foregroundColor(.secondary)
                    } label: {
                        Text("Occupancy")
                    }
                }
                if let fuelConsumption = transportation.fuelConsumption {
                    let canDeclarePrivatePowerConsumption = transportation
                        .transportationType
                        .canDeclarePrivatePowerConsumption
                    Entry {
                        Text(
                            ConsumptionMeasurement(
                                value: fuelConsumption,
                                unit: canDeclarePrivatePowerConsumption ? .kilowattHoursPer100Kilometers : .litersPer100Kilometers
                            )
                            .converted(to: .init(locale: self.locale))
                            .formatted()
                        )
                        .foregroundColor(.secondary)
                    } label: {
                        Text(
                            canDeclarePrivatePowerConsumption ? "Power consumption" : "Fuel consumption"
                        )
                    }
                }
            }
            if let description = self.consumption.description {
                Section {
                    Text(
                        verbatim: description
                    )
                    .multilineTextAlignment(.leading)
                }
            }
            if let createdAt = self.consumption.createdAt {
                Section(
                    footer: Group {
                        if self.consumption.generatedByRecurringConsumptionId != nil {
                            Text("This entry was automatically added via recurring consumptions.")
                                .multilineTextAlignment(.leading)
                        }
                    }
                ) {
                    if self.consumption.generatedByPvInvestmentId == nil {
                        Entry {
                            Text(
                                createdAt.dateValue(),
                                style: .date
                            )
                            .foregroundColor(.secondary)
                        } label: {
                            Text("Created")
                        }
                    }
                    if let updatedAt = self.consumption.updatedAt {
                        Entry {
                            Text(
                                updatedAt.dateValue(),
                                style: .date
                            )
                            .foregroundColor(.secondary)
                        } label: {
                            Text("Updated")
                        }
                    }
                }
            }
            if self.consumption.generatedByPvInvestmentId == nil {
                Section {
                    Button {
                        self.consumptionFormSheetMode = .duplicate
                    } label: {
                        Label("Duplicate", systemImage: "doc.on.doc.fill")
                    }
                }
            }
        }
        .navigationTitle(self.consumption.localizedTitle)
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                if self.consumption.generatedByPvInvestmentId == nil {
                    Button {
                        self.consumptionFormSheetMode = .edit
                    } label: {
                        Label(
                            "Edit",
                            systemImage: "square.and.pencil"
                        )
                    }
                }
            }
            ToolbarItem(placement: .navigationBarTrailing) {
                Button(role: .destructive) {
                    self.isDeleteConfirmationDialogPresented = true
                } label: {
                    Label(
                        "Delete",
                        systemImage: "trash"
                    )
                    .foregroundColor(.red)
                }
                .confirmationDialog(
                    "Delete Entry",
                    isPresented: self.$isDeleteConfirmationDialogPresented,
                    actions: {
                        Button(role: .destructive) {
                            try? self.firebase
                                .firestore
                                .delete(
                                    self.consumption,
                                    context: .current()
                                )
                            self.dismiss()
                        } label: {
                            Text("Delete")
                        }
                        Button(role: .cancel) {
                        } label: {
                            Text("Cancel")
                        }
                    },
                    message: {
                        Text("Are you sure you want to delete the entry?")
                    }
                )
            }
        }
        .sheet(
            item: self.$consumptionFormSheetMode
        ) { consumptionFormSheetMode in
            SheetNavigationView {
                ConsumptionForm(
                    mode: {
                        switch consumptionFormSheetMode {
                        case .edit:
                            return .edit(self.consumption)
                        case .duplicate:
                            return .prefill(self.consumption)
                        }
                    }()
                )
            }
        }
        .task {
            guard self.photovoltaicPlantInvestment == nil
                    && self.photovoltaicPlant == nil else {
                return
            }
            await self.loadPhotovoltaicData()
        }
    }
    
}

// MARK: - Entry

private extension ConsumptionView {
    
    /// A ConsumptionView Entry
    struct Entry<Label: View, Content: View>: View {
        
        // MARK: Properties
        
        /// A ViewBuilder closure providing the content.
        @ViewBuilder
        let content: () -> Content
        
        /// A ViewBuilder closure providing the label.
        @ViewBuilder
        let label: () -> Label
        
        // MARK: View
        
        /// The content and behavior of the view.
        var body: some View {
            HStack {
                self.label()
                Spacer()
                self.content()
            }
        }
        
    }
    
}
